# Generated by Django 6.0.7 on 2026-09-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_align_contribution_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlycontribution',
            options={'ordering': ['-effective_from']},
        ),
    ]
