# Generated by Django 6.0.7 on 2026-08-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('nid_number', models.CharField(max_length=30, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(choices=[('President', 'President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Executive Member', 'Executive Member'), ('General Member', 'General Member')], max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
